vim.keymap.set("n", "<Leader><Leader>", ":Telescope file_browser<CR>", { desc = "Browse files" })
vim.keymap.set("n", "<Leader>sb", ":Telescope buffers<CR>", { desc = "Search buffers" })
vim.keymap.set("n", "<Leader>sc", ":Telescope commands<CR>", { desc = "Search commands" })
vim.keymap.set("n", "<Leader>sd", ":Telescope diagnostics<CR>", { desc = "Search diagnostics" })
vim.keymap.set("n", "<Leader>sf", ":Telescope find_files<CR>", { desc = "Search files" })
vim.keymap.set("n", "<Leader>sh", ":Telescope help_tags<CR>", { desc = "Search help" })
vim.keymap.set("n", "<Leader>sk", ":Telescope keymaps<CR>", { desc = "Search keymaps" })
vim.keymap.set("n", "<Leader>so", ":Telescope oldfiles<CR>", { desc = "Search old files" })
vim.keymap.set("n", "<Leader>sr", ":Telescope resume<CR>", { desc = "Search resume" })
vim.keymap.set("n", "<Leader>ss", ":Telescope live_grep<CR>", { desc = "Search string" })
vim.keymap.set({ "n", "v" }, "<Leader>sw", ":Telescope grep_string<CR>", { desc = "Search word" })

vim.keymap.set({ "n", "t", "v" }, "<Leader>af", ":Sidekick cli focus<CR>", { desc = "Focus AI" })
vim.keymap.set({ "n", "v" }, "<Leader>ap", ":Sidekick cli prompt<CR>", { desc = "Prompt AI" })
vim.keymap.set("n", "<Leader>as", ":Sidekick cli select filter={installed=true}<CR>", { desc = "Select AI" })
vim.keymap.set("n", "<Leader>ac", ":Sidekick cli close<CR>", { desc = "Close AI" })
vim.keymap.set("n", "<Leader>at", ":Sidekick cli toggle focus=true<CR>", { desc = "Toggle AI" })
