vim.keymap.set("n", "<Space>", ":Telescope buffers<CR>", { desc = "Find buffers" })
vim.keymap.set("n", "-", ":Telescope file_browser<CR>", { desc = "Browse files" })

vim.keymap.set("n", "<Leader>fc", ":Telescope commands<CR>", { desc = "Find commands" })
vim.keymap.set("n", "<Leader>fd", ":Telescope diagnostics<CR>", { desc = "Find diagnostics" })
vim.keymap.set("n", "<Leader>ff", ":Telescope find_files<CR>", { desc = "Find files" })
vim.keymap.set("n", "<Leader>fh", ":Telescope help_tags<CR>", { desc = "Find help" })
vim.keymap.set("n", "<Leader>fk", ":Telescope keymaps<CR>", { desc = "Find keymaps" })
vim.keymap.set("n", "<Leader>fo", ":Telescope oldfiles<CR>", { desc = "Find old files" })
vim.keymap.set("n", "<Leader>fr", ":Telescope resume<CR>", { desc = "Find resume" })
vim.keymap.set("n", "<Leader>fs", ":Telescope live_grep<CR>", { desc = "Find string" })
vim.keymap.set({ "n", "v" }, "<Leader>fw", ":Telescope grep_string<CR>", { desc = "Find word" })

vim.keymap.set({ "n", "v" }, "<Leader>ap", ":Sidekick cli prompt<CR>", { desc = "Artificial prompt" })
vim.keymap.set("n", "<Leader>ac", ":Sidekick cli close<CR>", { desc = "Artificial close" })
vim.keymap.set("n", "<Leader>at", ":Sidekick cli toggle focus=true<CR>", { desc = "Artificial toggle" })
