container_always_pull="1"
container_generate_entry="0"
container_image_default="docker.io/library/archlinux:base-devel"
container_name_default="distrobox"
#container_init_hook="~/.config/distrobox/init.sh"
