set -g mouse on
set -g set-clipboard external
set -g copy-command wl-copy
set -g status-right ""

set -s escape-time 10

setw -g mode-keys vi

bind j choose-window "join-pane -h -s '%%'"

bind -T copy-mode-vi y send -X copy-pipe-and-cancel
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X begin-selection \; send -X rectangle-toggle
