# Allow mouse usage
set -g mouse on

# Set clipboard to use
set -g set-clipboard external
set -g copy-command wl-copy

# Set vi-like copy mode keymaps
set -g mode-keys vi

# Set emacs-like status keymaps
set -g status-keys emacs

# Always start counting from 1, not 0
set -g base-index 1
set -g pane-base-index 1

# Don't allow programs to change window name
set -g allow-rename off
set -g automatic-rename off

# Set right status
set -g status-right '"#{=20:pane_title}" W:#{window_index}/#{session_windows} S:#(tmux list-sessions | nl | grep '\'' (attached)$'\'' | awk '\''{print $1}'\'')/#{server_sessions}'

# Set theming for status and command
set -g status-style "fg=default,bg=default"
set -g message-command-style "fg=default,bg=default"
set -g message-style "fg=default,bg=default"
set -g prompt-cursor-colour default

# Unset default prefix key
unbind C-b

# Set my prefix key
set -g prefix F1

# Send prefix key to underlying process
bind F1 send-prefix

# Set my global keymaps
bind -n M-PgUp copy-mode
bind -n M-PgDn paste-buffer -p
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-< swap-pane -U
bind -n M-> swap-pane -D
bind -n M-[ previous-window
bind -n M-] next-window
bind -n M-\{ swap-window -t -1
bind -n M-\} swap-window -t +1
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-R source-file "~/.config/tmux/tmux.conf"
bind -n M-r command-prompt -I "#W" "rename-window -- '%%'"
bind -n M-w command-prompt "new-window -n '%%' -c '#{pane_current_path}'"
bind -n M-h split-window -h -c "#{pane_current_path}"
bind -n M-v split-window -v -c "#{pane_current_path}"
bind -n M-j choose-window "join-pane -h -s '%%'"
bind -n M-b break-pane
bind -n M-l next-layout
bind -n M-x kill-pane
bind -n M-X kill-window
bind -n M-K kill-server
bind -n M-z resize-pane -Z
bind -n M-d detach-client
bind -n M-s command-prompt "new-session -A -s '%%'"
bind -n M-o choose-tree -Zw
bind -n M-: command-prompt
bind -n M-p run -b "#{@fingers-cli} start #{pane_id}"
bind -n M-c display-popup -h 100% -w 100% -E "tmux capture-pane -p | nvim -R"

# Set copy mode keymaps
bind -T copy-mode-vi y send -X copy-pipe-and-cancel
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X begin-selection \; send -X rectangle-toggle
bind -T copy-mode-vi Escape send -X cancel

# Don't copy after text is selected with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Copy selected text with right mouse click
bind -T copy-mode-vi MouseDown3Pane send -X copy-pipe-and-cancel

# Add plugins
set -g @plugin "Morantron/tmux-fingers#fc3c750b8d73ac3e29675aae3b3ac6a00a0718f1"
set -g @plugin "hyoretsu/tmux-persist#d72e0b2073adcf33782cec63759d7f31cb58dbc0"
set -g @plugin "abhinav/tmux-fastcopy#71fdefc8fcd48505b741451345ec2414c6ebf214"
set -g @plugin "b0o/tmux-autoreload#e98aa3b74cfd5f2df2be2b5d4aa4ddcc843b2eba"
set -g @plugin "jaclu/tmux-menus#bc8e42f601f6c038ed23f68a4a086607a91a8d46"

# Configure plugins
set -g @fingers-alt-action ":paste:"
set -g @fingers-hint-position "right"
set -g @fingers-pattern-0 'HOMEBREW_[A-Z_=0-9]+ (?<match>.+)'
set -g @menus_without_prefix "Yes"
set -g @menus_trigger "M-m"
set -g @menus_config_file "~/.config/tmux/tmux.conf"

# Run package manager
run "tpack init"
