# Allow mouse usage
set -g mouse on

# Set clipboard to use
set -g set-clipboard external
set -g copy-command wl-copy

# Show no right status
set -g status-right ''

# Always start counting from 1, not 0
set -g base-index 1
set -g pane-base-index 1

# Don't allow programs to change window name
set -g allow-rename off

# Unset default prefix key
unbind C-b

# Set my prefix key
set -g prefix F1

# Send F1 to running program under tmux
bind F1 send-prefix

# Set my global keymaps
bind -n F2 copy-mode
bind -n F3 paste-buffer -p
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind -n M-[ previous-window
bind -n M-] next-window
bind -n M-\{ swap-window -t -1
bind -n M-\} swap-window -t +1
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-R source-file ~/.config/tmux/tmux.conf
bind -n M-r command-prompt -I "#W" "rename-window -- '%%'"
bind -n M-n command-prompt "new-window -n '%%' -c '#{pane_current_path}'"
bind -n M-N new-window -c "#{pane_current_path}"
bind -n M-h split-window -h -c "#{pane_current_path}"
bind -n M-v split-window -v -c "#{pane_current_path}"
bind -n M-j choose-window "join-pane -h -s '%%'"
bind -n M-b break-pane
bind -n M-w choose-tree -Zw
bind -n M-l next-layout
bind -n M-x kill-pane
bind -n M-X kill-window
bind -n M-f command-prompt -p "find-window" "find-window '%%'"
bind -n M-z resize-pane -Z
bind -n M-d detach-client
bind -n M-c copy-mode

# Set vi-like copy mode keymaps
setw -g mode-keys vi
bind -T copy-mode-vi y send -X copy-pipe-and-cancel
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X begin-selection \; send -X rectangle-toggle
bind -T copy-mode-vi Escape send -X cancel

# Don't copy after text is selected with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Copy selected text with right mouse click
bind -T copy-mode-vi MouseDown3Pane send -X copy-pipe-and-cancel
