#!/usr/bin/env bash

set -euo pipefail

read -rp $'\e[96m\e[1m==> \e[39mNuke unstaged changes? [y/N]\e[0m ' NUKE

if [[ "$NUKE" =~ ^[Yy]$ ]]; then
    root="$(git rev-parse --show-cdup)"
    root="${root:-.}"
    git clean -fd
    git checkout -- "${root}"
fi
