#!/usr/bin/env bash

set -euo pipefail

conflicted_files=()

while IFS= read -r -d '' file; do
   conflicted_files+=("$file")
done < <(git diff --name-only --diff-filter=U -z)

if ((${#conflicted_files[@]} == 0)); then
   echo 'No conflicted files.'
   exit
fi

"$EDITOR" -- "${conflicted_files[@]}"
