#!/usr/bin/env bash

set -xeuo pipefail

# Perform initial checks
if test $EUID -eq 0; then
    echo 'Do not run this script as root!'
    exit 127
fi

# Install homebrew
if ! test -e /home/linuxbrew/.linuxbrew/bin/brew; then
    sudo apt install -y build-essential procps curl file git
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
fi

# Check out my dotfiles to current user's home directory
if ! test -d ~/.dotfiles; then
    git clone --bare https://github.com/dawidd6/dotfiles ~/.dotfiles
    git --git-dir ~/.dotfiles config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
    git --git-dir ~/.dotfiles config --bool core.bare false
    git --git-dir ~/.dotfiles config core.worktree ~
    git --git-dir ~/.dotfiles fetch origin
    git --git-dir ~/.dotfiles branch --set-upstream-to origin/master master
    git --git-dir ~/.dotfiles checkout --force
fi

# Install packages from brewfile
if ! brew bundle check --global &>/dev/null; then
    brew bundle install --global
fi

# Set default shell to fish globally for current user
if ! grep -q /home/linuxbrew/.linuxbrew/bin/fish /etc/shells; then
    echo /home/linuxbrew/.linuxbrew/bin/fish | sudo tee --append /etc/shells
    sudo chsh --shell /home/linuxbrew/.linuxbrew/bin/fish "$(whoami)"
fi

# Install podman
if ! dpkg -s podman &>/dev/null; then
    sudo apt install -y podman
fi

# If on desktop then do these
if command -v gnome-shell &>/dev/null; then
    # Install incus
    if ! dpkg -s incus &>/dev/null; then
        sudo apt install -y incus spice-client-gtk
        sudo incus admin init --auto
        sudo adduser "$USER" incus
    fi

    # Remove snap
    if dpkg -s snapd &>/dev/null; then
        sudo apt autopurge snapd
    fi

    # Remove gamemode
    if dpkg -s gamemode &>/dev/null; then
        sudo apt autopurge gamemode
    fi

    # Fingerprint authentication everywhere with more tries
    if ! grep -q 'max-tries=5' /etc/pam.d/common-auth; then
        sudo pam-auth-update --enable fprintd
        sudo sed -i 's/max-tries=1/max-tries=5/' /etc/pam.d/common-auth
    fi

    # Match gdm scaling to user session settings
    if ! test -e /etc/xdg/monitors.xml; then
        sudo cp ~/.config/monitors.xml /etc/xdg/monitors.xml
    fi

    # Remove noto fonts (dejavu looks better for me)
    if dpkg -s fonts-noto-core &>/dev/null; then
        sudo apt purge -y fonts-noto-core
    fi

    # Revert to pre-24.04 ubuntu fonts (they are better, what the heck canonical?)
    if ! dpkg -s fonts-ubuntu-classic &>/dev/null; then
        sudo apt install -y fonts-ubuntu-classic
    fi

    # Correct fonts for gdm
    if grep -q 'Ubuntu Sans' /usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema.override; then
        sudo sed -i 's/Ubuntu Sans/Ubuntu/' /usr/share/glib-2.0/schemas/10_ubuntu-settings.gschema.override
        sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
    fi

    # Tweak gnome desktop settings
    gsettings set org.gnome.desktop.interface font-name 'Ubuntu 11'
    gsettings set org.gnome.desktop.interface monospace-font-name 'UbuntuMono Nerd Font 13'
    gsettings set org.gnome.desktop.interface document-font-name 'Sans 11'
    gsettings set org.gnome.desktop.wm.preferences titlebar-font 'Ubuntu Bold 11'
    gsettings set org.gnome.settings-daemon.plugins.power idle-dim false
    gsettings set org.gnome.settings-daemon.plugins.power idle-brightness 100

    # Disable ubuntu specific gnome extensions
    gnome-extensions disable ubuntu-dock@ubuntu.com
    gnome-extensions disable ding@rastersoft.com
fi
