#!/usr/bin/env bash

set -euo pipefail

state_file="${XDG_STATE_HOME:-$HOME/.local/state}/tmux-rr.sh"

function save() {
	: >"$state_file"
	for pane_id in $(tmux list-panes -a -F '#{pane_id}'); do
		cat >>"$state_file" <<-EOF
			$(tmux list-panes -t "$pane_id" -f "#{==:#{pane_id},$pane_id}" -F "
			session_name='#{session_name}'
			window_name='#{window_name}'
			window_layout='#{window_layout}'
			window_panes='#{window_panes}'
			pane_index='#{pane_index}'
			pane_current_path='#{pane_current_path}'
			pane_current_command='#{pane_current_command}'
			pane_base_index='#{pane-base-index}'")
			command='$(tmux show-options -t "$pane_id" -pqv @rr-command)'
			scrollback='$(tmux capture-pane -epJ -S 0 -t "$pane_id" | base64 -w120)'
			process
		EOF
	done
}

# shellcheck disable=2154,2329,1090
function restore() {
	function process() {
		if ((pane_index == pane_base_index)); then
			if ! tmux has-session -t "=$session_name" &>/dev/null; then
				pane="$(tmux new-session -dP -F '#{pane_id} #{pane_tty}' -s "$session_name" -n "$window_name" -c "$pane_current_path" sh -c "tmux wait-for tmux-rr; exec $SHELL -li")"
			else
				pane="$(tmux new-window -dP -F '#{pane_id} #{pane_tty}' -t "$session_name" -n "$window_name" -c "$pane_current_path" sh -c "tmux wait-for tmux-rr; exec $SHELL -li")"
			fi
		else
			pane="$(tmux split-window -dP -F '#{pane_id} #{pane_tty}' -t "$session_name:{end}" -c "$pane_current_path" sh -c "tmux wait-for tmux-rr; exec $SHELL -li")"
		fi
		tmux resize-pane -t "$session_name:{end}" -U 999
		read -r pane_id pane_tty <<<"$pane"
		if ((pane_index == pane_base_index + window_panes - 1)); then
			tmux select-layout -t "$session_name:{end}" "$window_layout"
		fi
		base64 -d <<<"$scrollback" >"$pane_tty"
		tmux wait-for -S tmux-rr
		tmux send-keys -l -t "$pane_id" "$(base64 -d <<<"$command")"
	}
	test -f "$state_file" && source "$state_file"
}

function clear() {
	rm -f "$state_file"
}

function init-bash() {
	cat <<-'EOF'
		__tmux_preexec() {
		    local cmd encoded

		    cmd=$(fc -ln -1)
		    cmd=${cmd#"${cmd%%[![:space:]]*}"}
		    encoded=$(printf %s "$cmd" | base64 | tr -d '\n')

		    tmux set-option -pt "$TMUX_PANE" @rr-command "$encoded"
		}

		__tmux_precmd() {
		    tmux set-option -pu -t "$TMUX_PANE" @rr-command 2>/dev/null
		}

		PS0='$(__tmux_preexec)'
		PROMPT_COMMAND="__tmux_precmd${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
	EOF
}

function init-fish() {
	cat <<-'EOF'
		function __tmux_preexec --on-event fish_preexec
		    set encoded (printf %s "$argv[1]" | base64 | tr -d '\n')
		    tmux set-option -pt "$TMUX_PANE" @rr_command "$encoded"
		end

		function __tmux_postexec --on-event fish_postexec
		    tmux set-option -pu -t "$TMUX_PANE" @rr-command 2>/dev/null
		end
	EOF
}

function init-zsh() {
	cat <<-'EOF'
		autoload -Uz add-zsh-hook

		__tmux_preexec() {
		    local encoded
		    encoded=$(printf %s "$1" | base64 | tr -d '\n')
		    tmux set-option -pt "$TMUX_PANE" @rr-command "$encoded"
		}

		__tmux_precmd() {
		    tmux set-option -pu -t "$TMUX_PANE" @rr-command 2>/dev/null
		}

		add-zsh-hook preexec __tmux_preexec
		add-zsh-hook precmd __tmux_precmd
	EOF
}

function help() {
	cat <<-'EOF'
		Usage: tmux-rr <COMMAND>

		Commands:
		  clear       Remove saved sessions state file
		  init-bash   Print bash shell integration code
		  init-fish   Print fish shell integration code
		  init-zsh    Print zsh shell integration code
		  save        Save all currently running sessions
		  restore     Restore all saved sessions
		  help        Print this message
	EOF
	exit 1
}

case "${1:-}" in
clear | init-bash | init-fish | init-zsh | save | restore)
	"$1"
	;;
*)
	help
	;;
esac
