#!/usr/bin/bash

set -euo pipefail

state_file="${XDG_STATE_HOME:-$HOME/.local/state}/tmux-rr.sh"

function save() {
    printf '%s\n' '#!/usr/bin/env bash' >"$state_file"
    for pane_id in $(tmux list-panes -a -F '#{pane_id}'); do
        cat >>"$state_file" <<SCRIPT
scrollback='$(tmux capture-pane -epJ -S 0 -t "$pane_id" | base64 -w120)'
SCRIPT
        tmux list-panes -t "$pane_id" -f "#{==:#{pane_id},$pane_id}" -F "$(
            cat <<'SCRIPT'
if (( #{pane_index} == #{pane-base-index} )); then
    if tmux has-session -t '=#{session_name}' 2>/dev/null; then
        pane="$(tmux new-window -dP -F '##{pane_id} ##{pane_tty}' -t '=#{session_name}' -n '#{window_name}' -c '#{pane_current_path}' sh -c "tmux wait-for tmux-rr; exec $SHELL -li")"
    else
        pane="$(tmux new-session -dP -F '##{pane_id} ##{pane_tty}' -s '#{session_name}' -n '#{window_name}' -c '#{pane_current_path}' sh -c "tmux wait-for tmux-rr; exec $SHELL -li")"
    fi
else
    pane=$(tmux split-window -dP -F '##{pane_id} ##{pane_tty}' -t "$pane" -T -c '#{pane_current_path}' sh -c "tmux wait-for tmux-rr; exec $SHELL -li")
fi
read -r pane_id pane_tty <<< "$pane"
base64 -d <<< "$scrollback" > "$pane_tty"
tmux wait-for -S tmux-rr
if (( #{pane_index} == #{pane-base-index} + #{window_panes} - 1 )); then
    tmux select-layout -t "$pane_id" '#{window_layout}'
fi
    
    
SCRIPT
        )" >>"$state_file"
    done
}

# TODO: is this needed?
# command="$(printf '%s' '#{@resurrect-command}' | base64 -d)"
# if [[ -n "$command" ]]; then
#     tmux send-keys -l -t "$pane_id" "$command"
# fi

function restore() {
    # shellcheck disable=SC1090
    source "$state_file"
}

function clear() {
    rm -f "$state_file"
}

case "${1:-}" in
save | restore | clear)
    "$1"
    ;;
*)
    echo "usage: $0 save|restore|clear"
    exit 127
    ;;
esac
