name: Setup Ubuntu

on:
  push:
    branches:
      - master
    paths:
      - .local/bin/setup-ubuntu
      - .github/workflows/setup-ubuntu.yml
  workflow_dispatch:

jobs:
  setup-ubuntu:
    runs-on: ubuntu-${{ matrix.ubuntu_release }}
    strategy:
      matrix:
        ubuntu_release:
          - "26.04"
    steps:
    - name: Install incus
      run: sudo apt update && sudo apt install -y incus

    - name: Initialize incus
      run: sudo incus admin init --auto

    - name: Run Ubuntu
      run: sudo incus launch --vm -c limits.cpu=2 -c limits.memory=2GiB -d root,size=50GiB images:ubuntu/${{ matrix.ubuntu_release }}/desktop vm

    - name: Wait up
      run: until sudo incus exec vm -- systemctl is-active gdm; do sleep 5; done

    - name: Install Homebrew
      run: sudo incus exec vm -- bash -c "$(wget -qO - https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Setup Ubuntu
      run: sudo incus exec vm -- bash -c "$(wget -qO - https://raw.githubusercontent.com/dawidd6/dotfiles/refs/heads/master/.local/bin/setup-ubuntu)"
